### PR TITLE
Initial Add

### PR DESCRIPTION
**Pull request by adamzero1**
Hope this is okay, I needed the AWS stuff to go along with the async events.
As the current aligent repo, looks for aligent classes.

- I've chaned all the namespaces etc..
- Added a plugin so that you can pick "AWS Event Bridge" for the ui module.

### CODE REVIEW

**Comment by gowrizrh** [comment]
Thanks for the PR :slightly_smiling_face:

However, this is already in the works

All event destinations are managed as a module in a mono-repository here.
https://github.com/mage-os/mageos-async-events-sinks/tree/main

https://github.com/mage-os/mageos-async-events-sinks/tree/main/MageOS/AsyncEventsAWS

Contributions are accepted on the main repo (once we have CI setup)

There has been work done on the AWS module however this is pending configuration changes within MageOS terraform
https://github.com/mage-os/terraform/issues/85

@Vinai @sprankhub

**Comment by adamzero1** [comment]
ta, can we get this repo deleted then? to stop others wasting time?

**Comment by gowrizrh** [comment]
this is supposed to be a distribution repo, ideally closed off with PRs and issues

**Comment by gowrizrh** [comment]
now that https://github.com/mage-os/terraform/issues/85 is closed, we should be able to release via CI and have everything setup.

once that's done, this repo should have the correct contributing instructions so that it is _very_ clear where to contribute. 

apologies if that was confusing for now as i've been trying to get this completed for a while.

**Comment by adamzero1** [comment]
great stuff thanks @gowrizrh do you know when this is being relesed as a package? (As the sink repo isn't in packagist)

**Comment by gowrizrh** [comment]
@adamzero1  i'm just finishing up testing and documentation :) hopefully it should be on packagist end of this week. this is the repo that will be on packagist

**Comment by gowrizrh** [comment]
@adamzero1 v4.0 is now released and available on packagist

```
composer require mage-os/mageos-async-events
composer require mage-os/mageos-async-events-aws
```

**Pull request closed without merging**
